nodeLinker: node-modules

packageExtensions:
  "@fastify/cors@*":
    peerDependencies:
      fastify: "4.x"
  "@fastify/multipart@*":
    peerDependencies:
      fastify: "4.x"
  "@fastify/static@*":
    peerDependencies:
      fastify: "4.x"
